# Generated by Django 5.2.1 on 2025-05-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_user_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='final_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='submitted_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
