# Generated by Django 5.2.1 on 2025-05-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_final_description_task_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='review_status',
            field=models.CharField(choices=[('NONE', 'None'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NONE', max_length=20),
        ),
    ]
